[9.0][MIG] website_sale_suggest_create_account: Upgrade to v9
OCA/e-commerce pull request #125
Opened 2016-09-17 03:31 UTC by lasley

This is the other half of #89 - website_sale_suggest_create_account, which I submitted out of order 😆

2016-09-17 09:20 UTC, pedrobaeza commented
Same comments about the commit than in #124

2016-09-17 09:21 UTC, pedrobaeza commented on website_sale_suggest_create_account/README.rst
> +e-commerce/issues/new?body=module:%20
Update this to latest version

2016-09-17 09:21 UTC, pedrobaeza commented on website_sale_suggest_create_account/__openerp__.py
> +    "author": "Antiun Ingeniería S.L., "
Please switch this to the new company `Tecnativa`

2016-09-17 09:22 UTC, pedrobaeza requested changes

2016-09-17 14:05 UTC, lasley commented on website_sale_suggest_create_account/__openerp__.py
> +    "author": "Antiun Ingeniería S.L., "
Copyrights too, or just this author key?

2016-09-17 14:34 UTC, lasley commented
@pedrobaeza - Updates made. Because I was rebasing and destroying our conversation anyways, I went ahead and just squashed the fix commit into my original.

I would love to hear if you have a strategy for removing that merge commit, but I can't figure out a way to combine the disparate parents without it.

Side note - now that I'm looking at Github, comments aren't being collapsed after being handled anymore. Double edged sword because our conversations aren't erroneously destroyed on rebasing, but now verifying what was done just became incredibly more difficult 😦

2016-09-18 15:53 UTC, pedrobaeza commented
Yeah, the comments not dissapearing seems a bit odd. Maybe they will dissapear when approving changes...

Please remove also the merge commit and you can also squash all the Yajo's commits in one.

2016-09-18 18:05 UTC, lasley commented
@pedrobaeza - How do I remove the merge commit? These were disparate parents because the module was not on 9.0. Is there some sort of wizardry that I don't know about here? It's part of the migration instructions as well, so we should update if you've got something fancy up your sleeve.

Will do on the squashing.

2016-09-18 22:35 UTC, pedrobaeza commented
Other times that I made the method where the module is not in branch, I didn't have a merge commit, so I'm not sure why it appears. Anyway, please try the new experimental mode, that also works when the module doesn't exist, and thus we can see if we switch the instructions to this one.

2016-09-19 06:40 UTC, lasley commented
@pedrobaeza - Done

That new process was really difficult, there were conflicts almost every step of the way. I feel like I was doing something wrong, but I repeated it a few times. Can you point me to where this development is happening? I don't see an issue in maintainer-tools?

2016-09-19 07:54 UTC, pedrobaeza commented
It happened in the mailing list (some prefer this channel because is more "general audience"): https://odoo-community.org/groups/contributors-15/contributors-44716?mode=thread&date_begin=&date_end=

2016-09-20 06:32 UTC, lasley commented
Thanks @pedrobaeza - I'll mess around locally a bit more then bring it to that thread. 

For the moment I reset then did some hilariously ghetto cherry-picks off of the backup from my initial branch which seem to have achieved the intended results.

2016-09-20 07:22 UTC, pedrobaeza approved these changes

2016-10-16 15:53 UTC, pedrobaeza commented
Merging this one to speed up PR treatment.

2016-10-16 15:53 UTC, merged