[9.0][MIG][website_sale_checkout_country_vat] Migrate.
OCA/e-commerce pull request #132
Opened 2016-09-30 11:28 UTC by Yajo

Migrated to v9, with corresponding changes.

@Tecnativa

2016-09-30 14:12 UTC, lasley approved these changes
Looks good 👍 

Also TIL `Website Snippet Country Code Dropdown` - spiffy

2016-09-30 15:01 UTC, pedrobaeza requested changes
You should squash also in pairs the two 8.0 commits from you, the OCA transbot and the removal of the en language, and finally your two 9.0 commits (till now). You can leave separated for now the commit amending these review, but we should squash it at the end also. The last 2 can be leaved until the "final squash" before merging.

2016-09-30 15:01 UTC, pedrobaeza commented on website_sale_checkout_country_vat/README.rst
> +when a customer makes a purchase and do the checkout process the VAT country
s/when/When

2016-09-30 15:01 UTC, pedrobaeza commented on website_sale_checkout_country_vat/README.rst
> +when a customer makes a purchase and do the checkout process the VAT country
comma after `checkout process`

2016-09-30 15:01 UTC, pedrobaeza commented on website_sale_checkout_country_vat/README.rst
> +code can be selected separated from the code itself.
You can add:
```
This is useful in 2 ways:

- User is implicitly forced to input (select) a country with its code.
- Error in the VAT now only can be raised by an incorrect vat, not the absence of the country code, which usually confuses user.
```

2016-09-30 15:01 UTC, pedrobaeza commented on website_sale_checkout_country_vat/__openerp__.py
> +    "category": "Website",
Isn't a specific category for e-commerce? We should create it if not.

2016-10-11 12:43 UTC, Yajo commented on website_sale_checkout_country_vat/__openerp__.py
> +    "category": "Website",
[`website_sale` has this](https://github.com/odoo/odoo/blob/9.0/addons/website_sale/__openerp__.py#L3)...

2016-10-11 12:48 UTC, yajo commented
Readme improved, commits logically squashed.

2016-10-11 12:59 UTC, pedrobaeza commented on website_sale_checkout_country_vat/__openerp__.py
> +    "category": "Website",
But as said, we are creating a new whole set of modules that should have an specific category although the main one is not differentiated.

2016-10-13 12:39 UTC, pedrobaeza commented on website_sale_checkout_country_vat/__openerp__.py
> +    "category": "Website",
Let's go this way for now, as there's no convention on this on the rest of the modules.

2016-10-13 12:39 UTC, pedrobaeza approved these changes

2016-10-13 12:39 UTC, merged