[9.0] [MIG] website_sale_require_legal module
OCA/e-commerce pull request #144
Opened 2016-11-28 11:37 UTC by cubells

* Updated README.rst

@Tecnativa

2016-11-28 21:47 UTC, pedrobaeza requested changes

2016-11-28 21:47 UTC, pedrobaeza commented on website_sale_require_legal/__openerp__.py
> +    "version": "9.0.1.1.0",
9.0.1.0.0

2016-11-28 21:47 UTC, pedrobaeza commented on website_sale_require_legal/README.rst
> +policy, and allow you to obey some countries' laws.
s/obey/comply with

2016-11-28 21:47 UTC, pedrobaeza commented on website_sale_require_legal/__openerp__.py
> +    "external_dependencies": {
Remove empty keys.

2016-11-28 21:53 UTC, pedrobaeza commented
Please rebase on current 9.0 branch, because I have fixed .travis.yml for allowing sass command.

2016-11-29 17:06 UTC, cubells commented
Is Travis error related to another module?

2016-11-29 21:27 UTC, pedrobaeza commented
Travis is failing due to website_sale_wishlist module, so not related.

2016-11-29 21:33 UTC, pedrobaeza commented
Please rebase again, as sass command is still not working.

2016-12-13 10:28 UTC, Yajo commented
This addon [breaks a tour in `website_sale_wishlist`](https://travis-ci.org/OCA/e-commerce/jobs/180007434#L1000-L1008). You have to fix that tour. It might not be an easy task for tour beginners, should I do that @pedrobaeza?

2016-12-13 12:10 UTC, pedrobaeza commented
The error is also on base branch, so it's not something of this branch. @Yajo, please fix it on another PR.

2016-12-13 12:45 UTC, Yajo commented
I hope #149 fixes it.

2016-12-22 12:15 UTC, Yajo commented
You need to rebase.

2017-01-05 10:28 UTC, yajo approved these changes
There's a coverage drop, but code & functional test passed.

2017-01-05 21:05 UTC, pedrobaeza approved these changes

2017-01-06 09:51 UTC, merged