[website_sale_b2c_v10] B2C mode in e-commerce
OCA/e-commerce pull request #173
Opened 2017-04-28 11:14 UTC by Yajo

This is a functional backport form Odoo 10's B2C mode. Allows you to display prices with taxes included in the online shop.

@Tecnativa

2017-04-28 12:27 UTC, pedrobaeza requested changes
I miss some tests for checking computed fields (not website part).

2017-04-28 12:27 UTC, pedrobaeza commented on website_sale_b2c_v10/README.rst
> +* When upgrading your database to Odoo 10.0, you will have to uninstall this
This is not needed if migration scripts are provided on OpenUpgrade, so just put "This module is not needed on v10 and without proper migration scripts, a version 9 upgraded DB can have problems".

2017-04-28 12:27 UTC, pedrobaeza commented on website_sale_b2c_v10/README.rst
> +Funders
Remove this section, as it's used for crowdfunding and similar, and actually it hasn't been funded by Tecnativa, but the customer. Anyway, the customer here doesn't want to appear.

2017-04-28 12:28 UTC, pedrobaeza commented
@chienandalu @luismontalba please review this functionally. Do you understand the purpose?

2017-04-28 12:38 UTC, Yajo commented
Now that you point at it @pedrobaeza... I was writing the tests, but I found extremely difficult to recreate the data to work with. Basically: A product template with 2 variants, one of which needs a price supplement, and with at least one tax.

I did not want to lose so much time in testing an addon with such a short life span, but do you have any recipe for creating that data?

Thanks.

2017-04-28 12:40 UTC, pedrobaeza commented
Well, I don't have it, but it's what you have mentioned. Not too much records to create IMO...

2017-05-02 14:20 UTC, chienandalu commented
I understand it @pedrobaeza but runbot is not rebuilding :-/

2017-05-02 14:36 UTC, pedrobaeza commented
OK, wait as there are 58 in queue that hasn't been executed yet. This is due to the "OCA Transbot" translations commits that are getting late this week. You can see in the runbot top part this status:

![seleccion_001](https://cloud.githubusercontent.com/assets/7165771/25622670/6c89d526-2f55-11e7-84bd-675e31066ed7.png)

2017-06-01 05:13 UTC, pedrobaeza approved these changes

2017-06-01 05:14 UTC, pedrobaeza commented
@sergio-teruel please review

2017-08-14 09:43 UTC, chienandalu approved these changes
@Yajo @pedrobaeza I've just patched with a little fix so taxes aren't added to the computed price for every company tax configured in the product template.

For instance, if I had in a product two company taxes the calculation was:

`pricelist_price + tax_company_1 + tax_company_2`

That aside, I've done the functional testing and everything seems ok

2017-08-14 11:01 UTC, pedrobaeza commented
@cubells please review

2017-08-14 20:52 UTC, cubells requested changes
there is no translation file.

Review travis because tests are failing.

2017-08-14 20:52 UTC, cubells commented on website_sale_b2c_v10/__openerp__.py
> +    "author": "Tecnativa",
README file says module is maintained by OCA. Where is OCA here?

2017-08-14 20:52 UTC, cubells commented on website_sale_b2c_v10/README.rst
> +* No tests.
There is not tests? Sure?

2017-08-14 20:52 UTC, cubells commented on website_sale_b2c_v10/models/sale_order_line.py
> +    discounted_price = fields.Float(compute="_fnct_get_discounted_price")
In theory, compute method must start with _compute

2017-08-18 08:53 UTC, chienandalu commented on website_sale_b2c_v10/models/sale_order_line.py
> +    discounted_price = fields.Float(compute="_fnct_get_discounted_price")
They are Odoo core methods

2017-08-18 08:55 UTC, chienandalu commented
@pedrobaeza @cubells I just sent a patch to fix a bug in the shown price when quantities are changed in the product page. Could you review again? Thanks!

2017-08-18 09:22 UTC, cubells requested changes
Tests are failing. Please review.

2017-08-18 09:28 UTC, elicoidal requested changes
I am very uncomfortable with the name of the module including the version...
I assume there might be a reason for that but honestly even though would strongly suggest to find a better name

2017-08-18 09:30 UTC, pedrobaeza commented
@elicoidal, yes, there's a very strong reason, and no, it mustn't be removed. Please check the README where all is perfectly explained, including its lifetime.

2017-08-18 09:33 UTC, pedrobaeza commented
This is the text:

`This is a functional backport form Odoo 10's B2C mode. Allows you to display prices with taxes included in the online shop.`

2017-08-18 09:42 UTC, elicoidal commented
@pedrobaeza The name should reflect the function, not the version. Besides it is even more confusing because naming suggest that this is for v10 actually while this is the other way around.
I still do not see any reason to have the version while it is perfectly explained in the README where and how to use this module.

2017-08-18 09:46 UTC, pedrobaeza commented
No, it doesn't suggest that. The module version is clear. The name indicates exactly the functionality: these are the B2C prices feature from v10. 

This technique is used in a lot of modules, even already merged (https://github.com/OCA/web/tree/10.0/web_widget_domain_v11).

2017-08-18 10:05 UTC, elicoidal commented
I still do not think that is a good idea: you dont care whether it has been backported or forwardported from where. Modules names should not be linked to versions but functions: otherwise are you gonna start renaming account_analytic_v8 because we forward port the function? 
Version does not bring clarity and brings a lot more issues and questions.
You can always explain where the function comes from in the README (as you did).

2017-08-18 10:08 UTC, pedrobaeza commented
I repeat: this is a very special case, as this is something only valid for this version and it helps to identify that migrating a v9 DB, this module should be removed. I vote for keeping this name.

2017-08-21 09:25 UTC, Yajo commented
Hi there @elicoidal, this is a common pattern that happened many times. It's an explicit way to say that an addon backports feature X from version Y. It also means that no migrations to that version should be done. So to speak, we call this addon with an ugly name to make sure you understand it's a temporary addon that will not be required in v10+. Also this way you know you should expect the same behavior as if you were in v10, an easy way to spot bugs.

it's not the same as when Odoo removes a feature in v10 that was present in v8. If we forward-port that, it's because it's a feature that exists no more, and as such the addon will not be volatile for just one version, but will be maintained for the foreseeable future. In those cases, adding the version to the name makes no sense indeed.

2017-08-21 09:27 UTC, Yajo commented
@chienandalu it seems that this feature breaks some other tours, possibly ones that expect to check the product price. Any ideas on how to fix that?

2017-08-21 10:27 UTC, chienandalu commented
@Yajo Well, it seems that website_sale_qty dislikes this part of the patch: https://github.com/OCA/e-commerce/pull/173/commits/4657cdbfca5bb64ce1640208eaf58fe911272751#diff-0cbe07dd41a95cc435ca24c4954a29ed Anyway, on a step by step check of its tests I'm getting the same result from super and in the end of the override (as it should be when no b2c is set). So no clue on why it's failing :confused:

2017-08-22 01:19 UTC, elicoidal commented
@yajo I understand the constraints or needs and the message. Still I do not think using the name is good enough/useful/rightful. And sorry to say: but you have to provide a 10-line extra explanation to it so it is definitively not a good way. Nobody in Odoo world uses this convention except for some exceptions in our repo: give the volume and audience, we should not maintain/incentive this kind of exceptions.
Explanation should be provided in the README file where it belongs with all necessary warnings and alarm bells.

@lasley @dreispt @jgrandguillaume @sbidoul @jbeficent @gurneyalex

2017-08-22 08:48 UTC, Yajo commented
OK, nevermind, renamed.

2017-08-22 10:12 UTC, Yajo commented
There was a bug on pricelist price computation, it's now fixed (and code is clearer by using unpacking) so tests should go 💚 now.

2017-08-22 12:46 UTC, elicoidal approved these changes

2017-08-22 13:47 UTC, cubells approved these changes
:+1: 

LGTM

2017-08-22 14:11 UTC, pedrobaeza approved these changes

2017-08-22 14:12 UTC, merged