[MIG] website_sale_cart_selectable: Migration to 10.0
OCA/e-commerce pull request #192
Opened 2017-07-13 16:23 UTC by chienandalu

Website Sale Cart Selectable
============================

This module was written to extend the functionality of the website to control
button add to cart. Button add to cart can now be set to be published or not.

cc @Tecnativa

2017-07-20 18:21 UTC, pedrobaeza requested changes

2017-07-20 18:21 UTC, pedrobaeza commented on website_sale_cart_selectable/views/product_view.xml
> +                    <field name="website_btn_addtocart_published"/>
Why do you remove the toggle widget?

2017-07-21 07:18 UTC, chienandalu commented on website_sale_cart_selectable/views/product_view.xml
> +                    <field name="website_btn_addtocart_published"/>
@pedrobaeza That widget is for stat buttons now. I could put this configuration in the button box, but I thought it belonged to the place where it used to be. I don't know if there is in v10 a widget similar to that one, do you?

2017-07-21 07:22 UTC, pedrobaeza commented on website_sale_cart_selectable/views/product_view.xml
> +                    <field name="website_btn_addtocart_published"/>
OK, then change the README that tells about toggle.

2017-07-21 07:46 UTC, chienandalu commented on website_sale_cart_selectable/views/product_view.xml
> +                    <field name="website_btn_addtocart_published"/>
@pedrobaeza Changed

2017-07-21 07:49 UTC, pedrobaeza approved these changes

2017-07-21 08:09 UTC, elicoidal approved these changes
some nitpicking

2017-07-21 08:09 UTC, elicoidal commented on website_sale_cart_selectable/README.rst
> +This module was written to extend the functionality of the website to control
This module extends the functionality of the website to improve the control on the
button "Add to cart". Button  "Add to cart" can now be set to be published or not.

2017-07-21 08:09 UTC, elicoidal commented on website_sale_cart_selectable/README.rst
> +1.  Go to menu *Sales -> Products -> Products*
you could also use "#. " (nice to have)

2017-07-21 08:09 UTC, elicoidal commented on website_sale_cart_selectable/__manifest__.py
> +    'summary': 'Enables to controlling button add to cart per product',
Enables to control button Add to cart display per product

2017-07-21 08:19 UTC, chienandalu commented
Thanks for your review @elicoidal :slightly_smiling_face: Changes done and commits squashed.

2017-07-24 18:49 UTC, merged