[IMP] record metadata on registration and acceptance of conditions
OCA/e-commerce pull request #235
Opened 2018-06-01 15:45 UTC by chienandalu

Make the module GDPR compliant

cc @Tecnativa

2018-06-01 16:26 UTC, pedrobaeza approved these changes

2018-06-01 16:30 UTC, chienandalu commented
Can we fix the website_sale_wishlist .rst with a direct commit from here 219e1c07eba954b6bbf53bd9f3676ce8c51691c8 for this branch?

2018-06-01 16:32 UTC, pedrobaeza commented
Done, please rebase.

2018-06-01 17:14 UTC, chienandalu commented
Great, green now

@rafaelbn Can you review?

2018-06-04 09:09 UTC, yajo requested changes

2018-06-04 09:09 UTC, Yajo commented on website_sale_require_legal/controllers/main.py
> +                partner_id.sudo(website_user).message_post(body=metadata)
Please explain in README where to find acceptance metadata. One might think it will be in the SO instead.

2018-06-04 09:09 UTC, Yajo commented on website_sale_require_legal/controllers/main.py
> +                metadata += "\n".join(
![captura de pantalla de 2018-06-04 10-05-30](https://user-images.githubusercontent.com/973709/40908670-551db164-67df-11e8-80fc-f3e8d3969c42.png)


It seems you need to use `<br/>` instead.

2018-06-04 09:30 UTC, chienandalu commented
@Yajo Changes done

2018-06-04 12:10 UTC, yajo approved these changes

2018-06-04 12:47 UTC, merged