[12.0] [MIG] website_sale_hide_price
OCA/e-commerce pull request #254
Opened 2018-10-29 18:44 UTC by dbo-odoo

Migrated as-is.

Note that a discussion could be opened regarding the 'multi-website' feature that was added in Odoo 12.0.

It might make sense to modify the boolean field on the partner to a many2many relation between `res_partner` and `website_website`, so that this price-hiding feature might be made website-dependant.

I don't know if this makes sense or not, and if this kind of behavioural change if often added in a migration. In any case, the module seems to work fine in 12.0, albeit for all websites at once.

2019-06-17 07:24 UTC, chienandalu requested changes
Thanks @dbo-odoo !

> Note that a discussion could be opened regarding the 'multi-website' feature that was added in Odoo 12.0.

Yes, what you propose seems the way to do it. You can just add it to the known issues/roadmap section in case you don't have the time to implement it.

There seem to be an unrelated .travis error as well.

Some minor comments

2019-06-17 07:24 UTC, chienandalu commented on website_sale_hide_price/models/res_partner.py
> +# -*- coding: utf-8 -*-
```suggestion
```

2019-06-17 07:24 UTC, chienandalu commented on website_sale_hide_price/models/__init__.py
> +##############################################################################
Get rid of all this

2019-06-17 07:24 UTC, chienandalu commented on website_sale_hide_price/__manifest__.py
> +# -*- coding: utf-8 -*-
```suggestion
```

2019-06-17 07:24 UTC, chienandalu commented on website_sale_hide_price/__init__.py
> +# -*- coding: utf-8 -*-
```suggestion
```

2019-06-17 07:24 UTC, chienandalu commented on website_sale_hide_price/README.rst
> +=======================
Use OCA readme parts if possible :)

2019-06-17 07:24 UTC, chienandalu commented on website_sale_hide_price/__manifest__.py
> +    'version': '12.0.1.0.1',
```suggestion
    'version': '12.0.1.0.0',
```

2019-06-21 12:30 UTC, lorenzoallegrucci commented on website_sale_hide_price/i18n/it.po
> +msgstr ""
This translation is: "Mostra prezzi sul sito web"

2020-01-09 13:00 UTC, maitaoriana commented
Hi @dbo-odoo,  Could I solve @chienandalu reviews? That would be the only thing missing to merge this module?

2020-02-18 13:59 UTC, sotolucas commented
Hi @maitaoriana! Would you solve pending reviews?

2020-02-19 10:23 UTC, simahawk commented
@maitaoriana you can do your own review for starting, same for @sotolucas 

@chienandalu ping :)

2020-02-19 16:32 UTC, simahawk commented
replaced by #339

2020-02-19 16:32 UTC, closed without merging