[MIG] website_sale_category_megamenu: Migration to 11.0
OCA/e-commerce pull request #259
Opened 2018-11-22 09:38 UTC by remytms

Hi,

I've ported this module to 11.0. And then I refactored it to use the Customize Menu in the Odoo Website.

Before it looked like this:
![before](https://user-images.githubusercontent.com/17589077/48893997-f1b11780-ee41-11e8-96ad-f0de2979f7aa.png)

After:
![after](https://user-images.githubusercontent.com/17589077/48894005-f970bc00-ee41-11e8-918c-428341893a30.png)

And the Customize menu:
![after_customize](https://user-images.githubusercontent.com/17589077/48894035-02fa2400-ee42-11e8-82a6-de3aa0c6c388.png)

Waiting for your comments. :)

2018-12-05 10:47 UTC, robinkeunen approved these changes
_wrong tab sorry, trying to dismiss this review_

2018-12-05 10:49 UTC, simahawk commented
@robinkeunen English please :)

2019-05-27 10:57 UTC, sergio-teruel commented
Can we close this PR?

2019-05-27 14:18 UTC, remytms commented
@sergio-teruel This PR is not yet merge into OCA, I prefer to leave it open. I'm waiting for reviews. I'm ready to change anything that seems wrong to the community.
Thanks

2019-09-02 11:26 UTC, rafaelbn requested changes
Are you preserving commit  history? Thanks @remytms

2019-09-02 11:26 UTC, rafaelbn commented on website_sale_category_megamenu/README.rst
> +* Rafael Blasco <rafaelbn@antiun.com>
Please change to rafael.blasco@tecnativa.com

2019-09-02 11:26 UTC, rafaelbn commented on website_sale_category_megamenu/__manifest__.py
> +    "author": "Antiun Ingeniería S.L., Odoo Community Association (OCA)",
Hi, please add Tecnativa as we change from Antiun to Tecnativa

2019-09-02 11:29 UTC, rafaelbn commented
Maybe @mFlayyan is interested in review this PR and you @remytms could review his PR https://github.com/OCA/e-commerce/pull/127

Remember, per each PR you make you should review 3 PR from others! :smile:

2019-09-05 01:18 UTC, rafaelbn requested changes
As said there are missing commits from 2015 https://github.com/OCA/e-commerce/pull/82/commits
And from 2016 https://github.com/OCA/e-commerce/pull/135/commits

2019-09-05 01:18 UTC, rafaelbn commented on website_sale_category_megamenu/README.rst
> +* Antonio Espinosa <antonioea@antiun.com>
This email also doesn't exist any more, just leave the name

2019-09-05 01:19 UTC, rafaelbn commented
Hi @remytms :smile: 

> @sergio-teruel This PR is not merged yet into OCA, I prefer to leave it open. I'm waiting for reviews. I'm ready to change anything that seems wrong to the community.
Thanks

I reviewed ! thanks you!

2020-11-25 10:41 UTC, remytms commented
There is missing commit in my PR. I will not redo all the work. I have started from the 9.0 branch instead of the 8.0 branch. I close this PR.

2020-11-25 10:41 UTC, closed without merging