[MIG][12.0] website_sale_product_detail_attribute_image: Migration to v12.0
OCA/e-commerce pull request #314
Opened 2019-10-30 15:54 UTC by sergio-teruel

cc @Tecnativa TT20151

2019-10-31 08:41 UTC, sergio-teruel commented
@rafaelbn @Yajo Can you review?

2019-10-31 09:25 UTC, yajo requested changes

2019-10-31 09:25 UTC, Yajo commented on website_sale_product_detail_attribute_image/tests/test_website_sale_product_detail_attribute_image.py
> +    post_install=True
It's better that you use the provided decorators instead, because this has changed in v12 and those decorators provide compatibility.

2019-10-31 09:25 UTC, Yajo commented on website_sale_product_detail_attribute_image/__manifest__.py
> -        'data/demo.xml',
The file still exists. Either restore it here in the manifest, or remove the `demo.xml` file please.

2019-10-31 09:25 UTC, Yajo commented on website_sale_product_detail_attribute_image/tests/test_website_sale_product_detail_attribute_image.py
> +        attribute_dangerous = self.ProductAttribute.create({
I don't understand... Why are you creating all these records if they're not used in the tests? :thinking:

2019-10-31 09:30 UTC, sergio-teruel commented
Changes done!!

2019-10-31 12:35 UTC, yajo approved these changes

2019-11-04 10:29 UTC, pedrobaeza approved these changes

2019-11-04 10:29 UTC, pedrobaeza commented
/ocabot merge

2019-11-04 11:09 UTC, merged