[13.0][MIG] website_sale_product_attribute_filter_visibility: Migration to 13.0
OCA/e-commerce pull request #334
Opened 2020-01-30 18:44 UTC by Tardo

cc @tecnativa TT21703

2020-02-03 15:32 UTC, sergio-teruel requested changes

2020-02-03 15:32 UTC, sergio-teruel commented on website_sale_product_attribute_filter_visibility/views/product_attribute_views.xml
> +                    <button name="website_publish_button"
See now how Odoo adds this smart button here.. 
https://github.com/odoo/odoo/blob/800abfc7baa8461f6b7b5ece95fa7700d3cd872a/addons/website_sale/views/product_views.xml#L91

2020-02-03 15:34 UTC, sergio-teruel commented
See the website_published button
Here the product's form
![Selección_563](https://user-images.githubusercontent.com/7689807/73666343-f3f83e00-46a2-11ea-8ece-dd4dc9996498.png)
And here the attribute's form
![Selección_564](https://user-images.githubusercontent.com/7689807/73666368-01152d00-46a3-11ea-9085-7912780de57f.png)

2020-02-06 18:02 UTC, Tardo commented
Change done! Now uses 'website_publish_button' widget.

2020-02-17 21:02 UTC, sergio-teruel commented
@Tardo fix travis.... pre-commit... pre-commit!!! :smile:

2020-02-18 19:41 UTC, Tardo commented
Done!

2020-02-18 21:18 UTC, sergio-teruel approved these changes

2020-03-02 18:48 UTC, Tardo commented
ping @chienandalu

2020-03-30 15:53 UTC, Tardo commented
ping @chienandalu

2020-04-15 11:28 UTC, chienandalu approved these changes
Functional tests :+1: 

Some minor and non blocking remarks

2020-04-15 11:28 UTC, chienandalu commented on website_sale_product_attribute_filter_visibility/README.rst
> +* Go to 'Sales > Settings > Product Attributes'.
```suggestion
* Go to *Website > Settings > Attributes*.
```

2020-04-15 11:28 UTC, chienandalu commented on website_sale_product_attribute_filter_visibility/__manifest__.py
> +    "development_status": "Beta",
Isn't it stable already?

2020-04-21 17:06 UTC, Tardo commented
Changes done

2020-04-23 12:23 UTC, chienandalu approved these changes

2020-04-23 12:23 UTC, chienandalu commented
Thanks :)

2020-04-23 14:21 UTC, pedrobaeza commented
/ocabot merge

2020-04-23 14:22 UTC, pedrobaeza commented
/ocabot merge nobump

2020-04-23 15:00 UTC, merged