[12.0][website_sale_product_brand] add sidebar brands filter
OCA/e-commerce pull request #364
Opened 2020-05-27 14:32 UTC by mcojocaru

2020-05-28 12:17 UTC, feketemihai approved these changes

2021-01-22 09:24 UTC, chienandalu commented on website_sale_product_brand/__manifest__.py
> +    'version': '12.0.2.1.0',
No need to bump the version, the bot does it at merge already

2021-01-22 09:25 UTC, chienandalu requested changes
Please fix conflicts with main branch and rebase

2021-02-24 09:49 UTC, mcojocaru commented
@chienandalu fixed conflicts

2022-06-12 12:26 UTC, closed without merging