[12.0][ADD] website_sale_attribute_filter_price
OCA/e-commerce pull request #372
Opened 2020-06-03 18:44 UTC by Tardo

![pricefilter](https://user-images.githubusercontent.com/731270/83676357-d5676c80-a5da-11ea-96a3-63be0cb4cb12.gif)

cc @tecnativa TT23634

2020-06-04 06:24 UTC, chienandalu reviewed
* Check travis
* There's some issue loading the lib assets:
![image](https://user-images.githubusercontent.com/5040182/83722106-b39ed180-a63c-11ea-87f6-9e67f96bbf52.png)

2020-06-04 06:24 UTC, chienandalu commented on website_sale_attribute_filter_price/controllers/website_sale.py
> +        )
The lint error comes from here
```suggestion
        request.env.context = dict(
            request.env.context,
            price_vals=[custom_min_price, custom_max_price])
```

2020-06-04 06:56 UTC, pedrobaeza commented
Isn't there a slider in existing resources for not requiring an extra library?

2020-06-04 12:05 UTC, pedrobaeza requested changes
Two functional problems:

- Incorrect limits:

![Selección_009](https://user-images.githubusercontent.com/7165771/83754524-62a6d180-a66c-11ea-98ec-49178eaba555.png)

The same may happen when you search for a text, and also applies to the minimum value.

- No price filter:

![Selección_010](https://user-images.githubusercontent.com/7165771/83754569-72261a80-a66c-11ea-8bd4-fad2eb3f6de9.png)

And check also that Travis is red

2020-06-05 15:13 UTC, chienandalu reviewed
A pair of usability problems I found

![price-filter](https://user-images.githubusercontent.com/5040182/83893059-c3f3a100-a74f-11ea-89d2-1dcec80d2f52.gif)

2020-06-08 16:47 UTC, Tardo commented
@chienandalu thanks. Improved the usability... but the problem with the 'Sort By' is a 'core' issue. This happens because the inputs can't use 'keep' method and the form doesn't have the 'order' value (as "input type='hidden'")

2020-06-09 06:27 UTC, chienandalu commented
Great. Being picky, one would expect to re-apply the filter once you click on the reset button
![erase-filter](https://user-images.githubusercontent.com/5040182/84113477-f7258100-aa2a-11ea-85eb-a4ce61c2f35e.gif)

2020-06-10 12:23 UTC, Tardo commented
@chienandalu changes made, removed all custom css and compatible with currency symbol position

![pricefilter](https://user-images.githubusercontent.com/731270/84267114-db52d580-ab25-11ea-94d7-69f25e2c10da.gif)

2020-06-10 14:35 UTC, chienandalu approved these changes
Great!

2020-06-10 14:37 UTC, pedrobaeza approved these changes

2020-06-10 14:37 UTC, pedrobaeza commented
/ocabot merge nobump

2020-06-10 16:08 UTC, merged