[MIG] product_template_multi_link: Migration to 14.0
OCA/e-commerce pull request #489
Opened 2021-02-02 11:45 UTC by chafique-delli

2021-03-22 10:10 UTC, dsolanki-initos approved these changes
Code review and Functional Tests. LGTM

2021-03-22 10:30 UTC, simahawk commented on product_template_multi_link/README.rst
> +.. image:: https://img.shields.io/badge/licence-AGPL--3-blue.svg
this README is outdated. Can you move to readme fragments?

2021-03-29 14:38 UTC, claudiagn approved these changes
functional review, LGTM!

2021-04-14 10:29 UTC, dsolanki-initos commented
It seems that PR is ready to merge

2021-04-23 08:35 UTC, dsolanki-initos commented
Can this be merged?

2021-04-23 08:50 UTC, chienandalu requested changes
https://github.com/OCA/e-commerce/pull/489#discussion_r598594845 wasn't attended. Please do

2021-04-30 05:51 UTC, dsolanki-initos commented
Hi @chafique-delli can you please resolve above comments so that we can merge this PR?

2021-05-03 09:54 UTC, simahawk approved these changes

2021-05-03 09:54 UTC, simahawk commented on product_template_multi_link/readme/CONTRIBUTORS.rst
> +* Sylvain LE GAL <http://www.twitter.com/legalsylvain>
* Laurent Mignon <laurent.mignon@acsone.eu>
* Simone Orsi <simahawk@gmail.com>

2021-05-07 10:43 UTC, dsolanki-initos commented
It would be great if we could merge this PR.

2021-05-10 07:47 UTC, chienandalu commented
Could you attend the last comment, please?

2021-05-13 07:29 UTC, dsolanki-initos commented
Hi @chafique-delli can you please have a look at the comments so that we can merge the PR ASAP.

2021-05-28 07:50 UTC, dsolanki-initos commented
Hi @chafique-delli It would be great if you could attend the comments

2021-06-04 11:48 UTC, dsolanki-initos commented
It would be great if you could attend the comments so that we can proceed further with the PR.

2021-06-08 06:04 UTC, simahawk commented
/ocabot merge nobump

2021-06-08 06:23 UTC, merged