[13.0][MIG][WIP] website_sale_tax_toggle: Migration
OCA/e-commerce pull request #497
Opened 2021-02-17 11:06 UTC by sergio-teruel

cc @Tecnativa TT27484

2021-02-18 16:32 UTC, chienandalu approved these changes
Tested :+1:

2021-02-22 07:48 UTC, CarlosRoca13 approved these changes
All working fine!! Just a non-blocking comment for tour loading

2021-02-22 07:48 UTC, CarlosRoca13 commented on website_sale_tax_toggle/demo/assets.xml
> +    <template id="assets_frontend_demo" inherit_id="website.assets_frontend">
```suggestion
    <template id="assets_tests_demo" inherit_id="website.assets_tests">
```
On v13 exists the the view assets_test. This assets are loaded just when testing, so you can place the file on templates and inherit from this view on data. Not need to place the assets on demo anymore

2021-02-22 07:54 UTC, CarlosRoca13 reviewed
Don't saw in last review the js variable definition 😅

2021-02-22 07:54 UTC, CarlosRoca13 commented on website_sale_tax_toggle/static/src/js/website_sale_tax_toggle.js
> +    var sAnimation = require("website.content.snippets.animation");
```suggestion
    const sAnimation = require("website.content.snippets.animation");
```

2021-02-22 07:54 UTC, CarlosRoca13 commented on website_sale_tax_toggle/static/src/js/website_sale_tax_toggle.js
> +            var $data = $(ev.currentTarget).parents(".js_tax_toggle_management:first");
```suggestion
            const $data = $(ev.currentTarget).parents(".js_tax_toggle_management:first");
```

2021-02-22 07:54 UTC, CarlosRoca13 commented on website_sale_tax_toggle/static/src/js/website_sale_tax_toggle_tour.js
> +    var base = require("web_editor.base");
```suggestion
    const tour = require("web_tour.tour");
    const base = require("web_editor.base");
```

2021-02-22 07:54 UTC, CarlosRoca13 commented on website_sale_tax_toggle/static/src/js/website_sale_tax_toggle_tour.js
> +    var steps = [
```suggestion
    const steps = [
```

2021-02-22 15:15 UTC, sergio-teruel commented
@CarlosRoca13 Changes done!!!

2021-02-22 15:38 UTC, CarlosRoca13 requested changes

2021-02-22 15:38 UTC, CarlosRoca13 commented on website_sale_tax_toggle/demo/assets.xml
> +    <template id="assets_tests_demo" inherit_id="website.assets_tests_demo">
```suggestion
    <template id="assets_tests_demo" inherit_id="website.assets_tests">
```

2021-02-24 12:14 UTC, sergio-teruel commented
@CarlosRoca13 Sorry!! Changes done!!

2021-03-03 10:28 UTC, CarlosRoca13 approved these changes

2021-03-07 02:49 UTC, pedrobaeza commented
/ocabot merge nobump

2021-03-07 07:09 UTC, merged