[14.0] [MIG] website_sale_stock_list_preview: Migration to 14.0
OCA/e-commerce pull request #640
Opened 2022-05-16 08:53 UTC by CarlosRoca13

@Tecnativa 

please @sergio-teruel @Tardo review this

2022-11-07 15:43 UTC, LudLaf requested changes
Take a look at the README

2022-11-07 15:43 UTC, LudLaf commented on website_sale_stock_list_preview/readme/DESCRIPTION.rst
> +the buyer the information about the stock on the preview of the products.
```suggestion
This module extends e-Commerce's functionality to give the buyer information about what's in stock when previewing the products
```

2022-11-07 15:43 UTC, LudLaf commented on website_sale_stock_list_preview/readme/USAGE.rst
> +* Edit some products on the option Availability of e-commerce
```suggestion
* Edit the 'Availability' option under 'eCommerce' tab in your selected product.
```

2022-11-07 15:43 UTC, LudLaf commented on website_sale_stock_list_preview/readme/USAGE.rst
> +* Go to the shop on the website and active Add to Cart view on Customize menu.
```suggestion
* Go to the website's shop and activate the 'Add to Cart' view under 'Customize' menu.
```

2022-11-07 15:43 UTC, LudLaf commented on website_sale_stock_list_preview/readme/USAGE.rst
> +* You can see on your products the results of the options that you had choose.
```suggestion

You can see, on your products, the options you have chosen.
```

2022-11-15 13:47 UTC, CarlosRoca13 commented
Changes done @LudLaf

2023-03-20 07:14 UTC, pedrobaeza commented
/ocabot migration website_sale_stock_list_preview

2023-05-04 08:17 UTC, pilarvargas-tecnativa approved these changes
locally tested :+1:

2023-05-05 17:43 UTC, pedrobaeza approved these changes
/ocabot merge nobump

2023-05-05 18:25 UTC, pedrobaeza commented
/ocabot merge nobump

2023-05-05 18:48 UTC, merged