[15.0][MIG]website_sale_checkout_skip_payment: Migration to 15.0
OCA/e-commerce pull request #654
Opened 2022-05-31 09:51 UTC by CarlosRoca13

cc @Tecnativa TT36598

please @sergio-teruel @Tardo review this

2022-05-31 10:16 UTC, CarlosRoca13 commented
This PR Superseds https://github.com/OCA/e-commerce/pull/632 

Adding the FIX https://github.com/OCA/e-commerce/pull/401 and fixing tests for v15

2022-06-02 18:25 UTC, sergio-teruel requested changes

2022-06-02 18:25 UTC, sergio-teruel commented on website_sale_checkout_skip_payment/README.rst
> +    :target: https://runbot.odoo-community.org/runbot/113/14.0
Please rebuild this file

2022-06-03 06:03 UTC, CarlosRoca13 commented
@sergio-teruel done

2022-06-03 11:04 UTC, sergio-teruel approved these changes

2022-09-05 15:28 UTC, ioans73 approved these changes
LGTM 👍🏻

2022-09-05 15:48 UTC, pedrobaeza commented
/ocabot migration website_sale_checkout_skip_payment
/ocabot merge nobump

2022-09-05 15:55 UTC, merged