12.0 update copier
OCA/e-commerce pull request #754
Opened 2023-02-15 16:49 UTC by victor-champonnois

@pedrobaeza

2023-02-20 15:05 UTC, victor-champonnois commented
How am I supposed to fix the following issue ?
```
Run manifestoo -d . check-dev-status --default-dev-status=Beta
website_sale_resource_booking (Production/Stable) depends on sale_resource_booking (Beta)
```
Should I put website_sale_resource_booking as beta ?

2023-02-20 20:02 UTC, pedrobaeza commented
Better to change `website_sale_resource_booking` to `Beta`.

2023-02-22 08:44 UTC, victor-champonnois commented
@pedrobaeza arghh, two modules are incompatible (they both replace the "vat" field in the views), so I excluded them in the manifests. Now the tests don't pass.

2023-02-24 18:52 UTC, pedrobaeza commented
Put them on the `rebel_module_groups` question for forcing them to be installed and tested separately. I think putting one of them is enough.

2023-05-10 09:50 UTC, carmenbianca approved these changes
LGTM

2023-05-11 08:45 UTC, victor-champonnois commented
@gurneyalex @gfcapalbo @simahawk this is ready to be merged

2023-05-16 10:06 UTC, SirTakobi requested changes
Thanks for the PR!
Just asking for clarification for a few obscure changes

2023-05-16 10:06 UTC, SirTakobi commented on .copier-answers.yml
> +dependency_installation_mode: OCA
The default is PIP (https://github.com/OCA/oca-addons-repo-template/blob/fe5b6f5c35c3d13822d080a9c9e20df209f3a6c5/copier.yml#L114), is there any specific reason why OCA is selected instead?

2023-05-16 10:06 UTC, SirTakobi commented on .copier-answers.yml
> +- website_sale_vat_required
In Travis configuration only **website_sale_vat_required** had a dedicated test environment, why with Copier is it needed for **website_sale_checkout_country_vat** too?

2023-05-16 12:17 UTC, victor-champonnois commented on .copier-answers.yml
> +dependency_installation_mode: OCA
no reason. It must have been a mistake. It's fixed

2023-05-16 12:24 UTC, victor-champonnois commented on .copier-answers.yml
> +- website_sale_vat_required
I don't really how github CI works, but having website_sale_checkout_country_vat in the common test environment didn't work. `website_sale_vat_required` and `website_sale_checkout_country_vat` are not compatible (due to a "replace" position in the views)

2023-05-16 12:30 UTC, SirTakobi commented on .copier-answers.yml
> +- website_sale_vat_required
If the modules are not compatible, that should be stated in the modules (with `excludes` keyword in the manifest), not just the CI configuration.

Still seems strange that they are not compatible just now, but Travis didn't use to complain.
What do you mean with _didn't work_? Is there an error shown in some log?

2023-09-18 07:26 UTC, carmenbianca commented
bump to un-stale

2023-09-18 07:27 UTC, pedrobaeza commented
There's still some red condition.

2023-09-18 07:40 UTC, carmenbianca commented
I'll have a look at removing the red.

2023-09-18 09:36 UTC, carmenbianca commented
Hopefully fixed, copy-pasting commit message below.

Should I mark these two modules incompatible somewhere in the manifest? Not sure how to do that. Five minutes of duckduckgo'ing haven't resulted in me finding an 'incompatible' field.

---

[FIX] website_sale_checkout_country_vat: Make simultaneously installable with website_sale_vat_required

These need to be simultaneously installable for runboat to function.

The problem: They both edit/replace the 'vat' element in the address
form in the e-commerce. website_sale_checkout_country_vat replaces it
with a country dropdown thing, and website_sale_vat_required replaces it
with a near-identical element that is mandatory to fill in instead of
optional.

_Technically_ both modules eventually end up with a <input ...
name="vat"/> element which they are both replacing, which means that the
modules would be replacing the same element, theoretically making them
both simultaneously installable. However,
website_sale_checkout_country_vat calls a template to create that
element, and Odoo isn't quite smart enough to do a replace on an element
created by a template call.

The solution to the problem is to make the existing vat element
invisible in website_sale_checkout_country_vat. This means that
website_sale_vat_required can easily find an element to replace.

In any case, these modules are _not_ compatible with one another without
spending some effort.

One downside of this fix is that there are now two 'vat' elements on the
page: one visible created by the template call and one marked invisible.
The former one is listed first, and therefore used when getting the
data. However, there may be a scenario where this could break stuff,
maybe. I just haven't found it.

2023-09-18 09:42 UTC, carmenbianca commented
OK I found the 'excludes' keyword for the manifest, but it breaks runboat, because it tries to install both.

2024-02-25 12:21 UTC, closed without merging