[16.0][MIG] website_sale_vat_required
OCA/e-commerce pull request #783
Opened 2023-04-19 14:09 UTC by Abranes

Migration to 16.0

2023-04-19 14:14 UTC, chienandalu requested changes
Check tours

2023-04-20 10:46 UTC, Abranes commented
> Check tours

@chienandalu I modified the test according to Odoo 16.0 `shop_buy_product` tour test:
https://github.com/odoo/odoo/blob/83613b56cadf1a12331db9d4d41ab688d68768e9/addons/website_sale/tests/test_sale_process.py#L69-L79

As you can see, Odoo now requires the `payment_custom` module to execute the `shop_buy_product` tour, which means that in our case, this test would not be executed since we do not depend on that module.

2023-08-21 06:03 UTC, chienandalu commented
> As you can see, Odoo now requires the `payment_custom` module to execute the `shop_buy_product` tour, which means that in our case, this test would not be executed since we do not depend on that module.

But then we're not performing the tests at all and we won't detect regressions automatically. If the Odoo core tour is useless now, we should discard it and do our own

2023-09-01 09:57 UTC, pilarvargas-tecnativa commented on website_sale_vat_required/tests/test_website_sale_vat_required.py
> +        if self.env["ir.module.module"]._get("payment_custom").state != "installed":
Functionality tested locally, thank you!
I agree with David, the tests should be changed as this step can be avoided to test this module without relying on the payment methods module. @Abranes what do you think about making the change?

2023-09-07 15:04 UTC, pilarvargas-tecnativa commented
Superseed by: https://github.com/OCA/e-commerce/pull/841

2023-09-07 16:10 UTC, closed without merging