[16.0][MIG] website_sale_product_attribute_filter_collapse: Migration to version 16.0
OCA/e-commerce pull request #825
Opened 2023-08-09 15:46 UTC by pilarvargas-tecnativa

cc @Tecnativa TT44382

@chienandalu @CarlosRoca13 please review :)

2023-08-09 15:49 UTC, pedrobaeza commented
/ocabot migration website_sale_product_attribute_filter_collapse

2023-08-10 13:01 UTC, chienandalu requested changes

2023-08-10 13:01 UTC, chienandalu commented on website_sale_product_attribute_filter_collapse/views/templates.xml
> -        name="Collapsible attribute filters"
Why removing this?

2023-08-10 13:01 UTC, chienandalu commented on website_sale_product_attribute_filter_collapse/views/templates.xml
> -        active="False"
Well, this changes the default behavior of the module. You should keep it IMO

2023-08-10 14:00 UTC, pilarvargas-tecnativa commented on website_sale_product_attribute_filter_collapse/views/templates.xml
> -        active="False"
I was adapting the configuration to the web editor but I deleted more than I should have. It is now restored as it was and the behaviour has been corrected to be the same. thanks

2023-08-10 14:05 UTC, chienandalu approved these changes
Now is great :slightly_smiling_face: :+1:

2023-08-11 05:21 UTC, CarlosRoca13 reviewed
Please set correct version

2023-08-11 05:21 UTC, CarlosRoca13 commented on website_sale_product_attribute_filter_collapse/__manifest__.py
> +    "version": "16.0.1.1.1",
```sugestion
    "version": "16.0.1.0.0",
```

2023-08-11 06:38 UTC, pilarvargas-tecnativa commented on website_sale_product_attribute_filter_collapse/__manifest__.py
> +    "version": "16.0.1.1.1",
thanks :)

2023-08-11 06:51 UTC, CarlosRoca13 approved these changes

2023-08-11 06:52 UTC, pedrobaeza commented
/ocabot merge nobump

2023-08-11 07:00 UTC, merged