[16.0][MIG] website_sale_invoice_address module
OCA/e-commerce pull request #837
Opened 2023-09-01 07:44 UTC by suker

Migration of module from 15.0 to 16.0

2023-09-01 09:59 UTC, chienandalu requested changes
Thanks @suker !

cc @Tecnativa @pilarvargas-tecnativa TT44888

tour fix suggestion:

2023-09-01 09:59 UTC, chienandalu commented on website_sale_invoice_address/static/src/js/website_sale_invoice_address_tour.js
> +            trigger: "a:contains('Large Meeting Table')",
I think this can fix your test
```suggestion
            trigger: "a:contains('Chair floor protection')",
```

2023-09-01 13:06 UTC, suker commented on website_sale_invoice_address/static/src/js/website_sale_invoice_address_tour.js
> +            trigger: "a:contains('Large Meeting Table')",
Yeah, thanks.

2023-09-01 15:38 UTC, chienandalu approved these changes
Thanks :)

2023-09-01 15:43 UTC, pedrobaeza commented
/ocabot migration website_sale_invoice_address

2023-09-05 08:52 UTC, liebana commented
Functional review, LGTM

2023-09-05 08:52 UTC, liebana approved these changes

2023-09-05 09:34 UTC, pedrobaeza commented
/ocabot merge nobump

2023-09-05 10:04 UTC, pedrobaeza commented
/ocabot merge nobump

2023-09-05 10:14 UTC, merged