[17.0] [MIG] website_sale_require_login
OCA/e-commerce pull request #973
Opened 2024-10-02 06:44 UTC by azimkhankuat

[17.0] [MIG] website_sale_require_login

2024-10-03 10:42 UTC, em230418 approved these changes
Code and functional review

2024-12-10 14:34 UTC, peluko00 reviewed
Change tests but LGTM

2024-12-10 14:34 UTC, peluko00 commented on website_sale_require_login/tests/test_website_sale_require_login.py
> +    def setUp(self):
Use setUpClass please

2024-12-16 07:49 UTC, em230418 commented
Suddenly found out, that it is already built-in function in Odoo.
![Снимок экрана_2024-12-16_12-47-59](https://github.com/user-attachments/assets/b24f6ba9-3b26-42bd-89cf-21ee5c856dfb)

2024-12-16 07:50 UTC, pedrobaeza requested changes
See the previous comment about already integrated in core.

2025-04-21 06:50 UTC, closed without merging